language: python
python:
- '3.8'
install:
- pip install mkdocs-material
- echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
script:
- mkdocs gh-deploy --force --clean
deploy:
  provider: pypi
  user: __token__
  password:
    secure: VDY2o7ALCnjB0dLd33vqwGuv+eXYt4fLnLNJUJZQLiNGjW/KvnCRa27wPwceDHJpy18+Geb+FLDQ0puPo9cqNwKYtJg/detTVLRzudEul5gpQtmJsuwoPeHR/oWHnFcAlyAXzzQn84tgxy6NI3WiEbvOziBKt2qign0aE5jRd7ybxsjsc+zavFQOls9J1EB3AuXi7j4bJlnJF7wsc7tkjKLo3YTcdpbineA/dbJ6gRqilGQA43pL8IwVJL/ovEKi/+ZFgouDvfox1V+PaR3IclNU4zB1keMpQwzTv7A8xxc41SPLPSVAJnGeB/iCsPYajpEqi+1CoGM+c/jtRfLsRzG4hE/vZDOxaLI0V2hxIISUp3wVrB6WKDMFeMdF3Mcc9LPyaD1ytguUF0HDlyYx6MF+vhVE9UXb45kLwjl7aal8qXwIcxmwhgZfMlGfr8EINOKJ2eWGmPGJNeVZv1y3W2VWnx3VqII7+LBxwtmPTdST/XSUKOC5l992IiqGqv391Eg7ct5jgl0F5OQiWR93ej//k4j0I6vcObqXFDhDQqCp/eOi3b/8efGCzd8OlRI/gbhF7j1kBxvP0Jvq/rEG8/eRuuKLATShFx7evu3c/hHj83+Ar0/qkszw1vx3fnciIhnDSOces+1k2H/VgSkzMeRTnVbFV2zf8brxIi6dkrI=
  on:
    branch: main
branches:
  only:
  - master
  - main
