language: python
python:
- '3.8'
install:
- pip install mkdocs-material
- echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
script:
- mkdocs gh-deploy --force --clean
deploy:
  provider: pypi
  user: __token__
  password: ${PYPI_TOKEN}
  on:
    branch: main
branches:
  only:
  - master
  - main
