language: python

python:
  - "3.8"

install:
  - pip install mkdocs-material
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs gh-deploy --force --clean

branches:
  only:
    - master
    - main