repo_url: https://github.com/Justin900429/GC-Detection
repo_name: Justin900429/GC-Detection

site_name: GC-Detection
theme:
  favicon: asset/favicon.png
  logo: asset/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  
  highlightjs: true
  hljs_languages:
    - yaml

  features:
    - navigation.tabs

  palette:
    primary: blue
    accent: green

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Justin900429/GC-Detection

copyright: Copyright &copy; 2021 - Justin Ruan and Joyce Fang

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.critic
  - attr_list